name: Preview Pull Request
description: Builds a pull request

inputs:
  pull-request-ref:
    description: The pull request number to preview
    required: true
  target-folder:
    description: The target folder to publish to
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.pull_request_ref }}
        submodules: recursive

    - name: publish preview
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: build-previews
        folder: public
        target-folder: ${{ inputs.target-folder }}

    - name: send comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: Preview environment
        message: |
          ## Preview environment
          https://brecert.github.io/workflow-testing/${{ inputs.target-folder }}/index.html

          This link will remain active until the `use-preview` label is removed.
