name: Clean Preview

#! Safety:
#! this workflow should not execute any code at all
#! see githubs docs on pull_request_target for more
on:
  pull_request_target:
    types: [closed]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: build-previews
          persist-credentials: false

      - run: 'rm -rf "./${{ github.event.pull_request.head.ref }}"'

      - name: Clean
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          folder: .
          branch: build-previews
