name: Clean Preview

on:
  pull_request:
    types: [closed]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir empty

      - name: Clean
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: build-previews
          folder: empty
          clean: true
          clean-exclude: "!${{ github.ref }}/**/*"
