name: Preview Commit

#! Safety:
#! this workflow should not execute any code at all
#! see githubs docs on pull_request_target for more
on:
  pull_request_target:
    types: [synchronize, reopened, labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'use-preview' || contains(github.event.pull_request.labels.*.name, 'use-preview')

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - runs: |
        echo "ref: ${{ github.event.pull_request_target.head.sha }}"

      - uses: ./.github/actions/preview_pull_request
        with:
          pull-request-ref: ${{ github.event.pull_request_target.head.sha }}
          target-folder: ./refs/pull/${{ github.event.pull_request.number }}
