name: Preview Commit

on: 
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'use-preview' || contains(github.event.pull_request.labels.*.name, 'use-preview')

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          # Head commit of PR
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: build-previews
          folder: public
          target-folder: ${{ github.ref }}

      - name: Send message
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Preview environment
          message: |
            ## Preview environment
            https://bree.dev/workflow-testing/${{ github.ref }}/index.html

            This link will remain active until the PR is closed, or the use-preview label is removed.
