name: Use Preview

#! Safety:
#! this workflow should not execute any code at all
#! see githubs docs on pull_request_target for more
on:
  pull_request:
    types: [synchronize, reopened, labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'use-preview' || contains(github.event.pull_request.labels.*.name, 'use-preview')

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
          persist-credentials: false

      - name: publish preview
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: build-previews
          folder: public
          target-folder: ${{ github.event.pull_request.head.sha }}

      - name: send comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Preview environment
          message: |
            ## Preview environment
            https://brecert.github.io/workflow-testing/${{ github.event.pull_request.number }}/index.html

            This link will remain active until the `use-preview` label is removed.
