name: Use Preview

#! Safety:
#! this workflow should not execute any code at all
#! see githubs docs on pull_request_target for more
on:
  pull_request_target:
    types: [synchronize, reopened, labeled]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'use-preview' || contains(github.event.pull_request.labels.*.name, 'use-preview')

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pull
          submodules: recursive

      - name: build
        uses: ./.github/actions/build
        with:
          folder: ./pull/

      - name: publish preview
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: build-previews
          folder: pull/public
          target-folder: refs/pull/${{ github.event.pull_request.number }}

      - name: send comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Preview environment
          message: |
            ## Preview environment
            https://brecert.github.io/workflow-testing/refs/pull/${{ github.event.pull_request.number }}/index.html

            This link will remain active until the `use-preview` label is removed.
